const RESOURCE_FIELDS = {
  quests:['title','category','difficulty','status','date','deadline','xp_reward','credit_reward','stat_id','skill_id','mission_id','priority','boss_quest','notes'],
  missions:['title','year','quarter','month','category','status','priority','deadline','progress','xp_reward','credit_reward','boss_fight','victory_condition','why_it_matters','notes'],
  skills:['name','category','status','skill_xp','target','deadline','source','source_url','notes'],
  books:['title','author','status','pages','pages_read','started','finished','category','notes'],
  school_tasks:['subject','task','type','status','priority','deadline','grade','estimated_min','actual_min','notes'],
  lessons:['subject','title','chapter','status','progress','deadline','notes'],
  study_sessions:['date','subject','minutes','focus_score','notes'],
  fitness_logs:['date','workout','type','duration','performance','energy','notes'],
  meals:['date','meal_type','food','water_ml','protein_note','energy','notes'],
  hygiene_logs:['date','shower','teeth_am','teeth_pm','skincare','hair','room','clothes','notes'],
  savings_goals:['goal','target','current','deadline','priority','status','notes'],
  finance_transactions:['date','description','type','amount','category','notes'],
  shopping_items:['item','price','priority','category','need_or_want','status','link','notes'],
  rewards:['reward','cost','category','description'],
  universities:['university','country','program','degree','deadline','status','scholarship','tuition','requirements','documents','website','priority','notes'],
  scholarships:['scholarship','organization','country','eligibility','deadline','status','amount','requirements','documents','website','notes'],
  quran_logs:['date','pages','minutes','surah','notes'],
  charity_logs:['date','amount','type','notes'],
  pomodoro_sessions:['date','started_at','ended_at','duration','subject','completed','notes'],
  stats:['name','description','stat_xp'],
  reviews:['kind','period','data']
};
const NUMS=new Set(['xp_reward','credit_reward','progress','month','year','skill_xp','pages','pages_read','estimated_min','actual_min','minutes','focus_score','duration','energy','water_ml','shower','teeth_am','teeth_pm','skincare','hair','room','clothes','target','current','amount','price','cost','boss_fight','grade','tuition','completed','stat_xp']);
const ALLOWED=new Set(Object.keys(RESOURCE_FIELDS));
const uid=()=>crypto.randomUUID();
const now=()=>new Date().toISOString();
const today=()=>new Date().toISOString().slice(0,10);
function b64u(bytes){let s='';for(const b of new Uint8Array(bytes))s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
function ub64(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0));}
async function keyFromSecret(secret){return crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);}
async function signToken(userId,env){const exp=Math.floor(Date.now()/1000)+Number(env.TOKEN_TTL_SECONDS||2592000);const data=`${userId}.${exp}`;const key=await keyFromSecret(env.TOKEN_SECRET||env.JWT_SECRET||'CHANGE_ME_NOW');const sig=await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(data));return `${b64u(new TextEncoder().encode(data))}.${b64u(sig)}`;}
async function verifyToken(token,env){try{const [a,b]=token.split('.');const data=new TextDecoder().decode(ub64(a));const [uid0,exp]=data.split('.');if(Number(exp)<Math.floor(Date.now()/1000))return null;const key=await keyFromSecret(env.TOKEN_SECRET||env.JWT_SECRET||'CHANGE_ME_NOW');const ok=await crypto.subtle.verify('HMAC',key,ub64(b),new TextEncoder().encode(data));return ok?uid0:null}catch{return null}}
async function hashPassword(p){const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},key,256);return `${b64u(salt)}:${b64u(bits)}`}
async function checkPassword(p,stored){try{const [sa,sh]=stored.split(':');const salt=ub64(sa);const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:120000,hash:'SHA-256'},key,256);const a=ub64(sh),b=new Uint8Array(bits);if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a[i]^b[i];return x===0}catch{return false}}
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8','cache-control':'no-store'}});
async function body(req){try{return await req.json()}catch{return {}}}
async function profile(env,u){const p=(await env.DB.prepare('SELECT * FROM profiles WHERE user_id=?').bind(u).first())||{};const xp=Number((await env.DB.prepare("SELECT COALESCE(SUM(xp_earned),0) xp FROM quests WHERE user_id=? AND status='Complete'").bind(u).first())?.xp||0);const cr=Number((await env.DB.prepare('SELECT COALESCE(SUM(amount),0) credits FROM credit_transactions WHERE user_id=?').bind(u).first())?.credits||0);const level=Math.floor(Math.sqrt(Math.max(0,xp)/250))+1;const lo=250*(level-1)**2,hi=250*level**2;const rank=level>=250?'SSS-RANK':level>=175?'SS-RANK':level>=120?'S-RANK':level>=80?'A-RANK':level>=50?'B-RANK':level>=25?'C-RANK':level>=10?'D-RANK':'E-RANK';const active=Number((await env.DB.prepare("SELECT COUNT(*) c FROM quests WHERE user_id=? AND status!='Complete'").bind(u).first())?.c||0);const done=Number((await env.DB.prepare("SELECT COUNT(*) c FROM quests WHERE user_id=? AND status='Complete'").bind(u).first())?.c||0);return {...p,totalXP:xp,credits:cr,level,rank,xpFloor:lo,xpCeiling:hi,xpToNext:Math.max(0,hi-xp),progress:Math.max(0,Math.min(1,(xp-lo)/Math.max(1,hi-lo))),activeQuests:active,completedQuests:done};}
async function ensureDay(env,u,d){await env.DB.prepare('INSERT OR IGNORE INTO daily_logs(id,user_id,date,created_at) VALUES(?,?,?,?)').bind(uid(),u,d,now()).run()}
async function dashboard(env,u){const d=today();await ensureDay(env,u,d);const prayer=(await env.DB.prepare('SELECT * FROM prayers WHERE user_id=? AND date=?').bind(u,d).first())||{date:d,fajr:0,dhuhr:0,asr:0,maghrib:0,isha:0};const pq=['fajr','dhuhr','asr','maghrib','isha'].reduce((a,k)=>a+Number(prayer[k]||0),0);const week=new Date(Date.now()-6*864e5).toISOString().slice(0,10);const xpweek=Number((await env.DB.prepare("SELECT COALESCE(SUM(xp_earned),0) x FROM quests WHERE user_id=? AND status='Complete' AND date>=?").bind(u,week).first())?.x||0);const finance=Number((await env.DB.prepare("SELECT COALESCE(SUM(CASE WHEN type='Income' THEN amount WHEN type='Expense' THEN -amount ELSE 0 END),0) x FROM finance_transactions WHERE user_id=?").bind(u).first())?.x||0);const q=await env.DB.prepare("SELECT * FROM quests WHERE user_id=? AND (date=? OR (status!='Complete' AND deadline<=?)) ORDER BY status='Complete', priority DESC, deadline LIMIT 30").bind(u,d,d).all();const school=await env.DB.prepare("SELECT * FROM school_tasks WHERE user_id=? AND status!='Complete' ORDER BY deadline LIMIT 6").bind(u).all();const lessons=await env.DB.prepare("SELECT * FROM lessons WHERE user_id=? AND status!='Complete' ORDER BY deadline LIMIT 6").bind(u).all();const books=await env.DB.prepare("SELECT * FROM books WHERE user_id=? AND status='Reading' LIMIT 5").bind(u).all();const skills=await env.DB.prepare('SELECT * FROM skills WHERE user_id=? ORDER BY skill_xp DESC LIMIT 8').bind(u).all();const missions=await env.DB.prepare("SELECT * FROM missions WHERE user_id=? AND status!='Complete' ORDER BY boss_fight DESC,deadline LIMIT 6").bind(u).all();const qt=await env.DB.prepare('SELECT COALESCE(SUM(pages),0) pages,COALESCE(SUM(minutes),0) minutes FROM quran_logs WHERE user_id=? AND date=?').bind(u,d).first();const overdue=Number((await env.DB.prepare("SELECT COUNT(*) c FROM quests WHERE user_id=? AND status!='Complete' AND deadline IS NOT NULL AND deadline<?").bind(u,d).first())?.c||0);return {profile:await profile(env,u),today:d,quests:q.results,prayer,prayerPct:pq*20,quranToday:qt,school:school.results,lessons:lessons.results,books:books.results,skills:skills.results,missions:missions.results,financeBalance:finance,xpWeek:xpweek,overdue};}
async function authUser(req,env){const a=req.headers.get('Authorization')||'';return a.startsWith('Bearer ')?verifyToken(a.slice(7),env):null}
async function handleApi(req,env,path){
 if(path==='/api/auth/signup' && req.method==='POST'){const b=await body(req);if(!b.email||!b.password||!b.hunterName||b.password.length<8)return json({error:'Name, email and password (8+ chars) are required.'},400);const id=uid();try{const ph=await hashPassword(b.password);await env.DB.batch([env.DB.prepare('INSERT INTO users(id,email,password_hash,created_at) VALUES(?,?,?,?)').bind(id,b.email.toLowerCase(),ph,now()),env.DB.prepare('INSERT INTO profiles(id,user_id,hunter_name,avatar,theme,timezone,currency,academic_year,bac_date,notifications,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(uid(),id,b.hunterName,'','dark','UTC','DZD','','',1,now()),...['Knowledge','Fitness','Skills','Language','Discipline','Spirit'].map(n=>env.DB.prepare('INSERT INTO stats(id,user_id,name,description,stat_xp,created_at) VALUES(?,?,?,?,?,?)').bind(uid(),id,n,'',0,now()))]);return json({token:await signToken(id,env),profile:await profile(env,id)})}catch(e){return json({error:'Account already exists or could not be created.'},400)}}
 if(path==='/api/auth/login' && req.method==='POST'){const b=await body(req);const r=await env.DB.prepare('SELECT * FROM users WHERE email=?').bind((b.email||'').toLowerCase()).first();if(!r||!(await checkPassword(b.password||'',r.password_hash)))return json({error:'Invalid login details.'},401);return json({token:await signToken(r.id,env),profile:await profile(env,r.id)})}
 const u=await authUser(req,env);if(!u)return json({error:'Unauthorized'},401);
 if(path==='/api/me'&&req.method==='GET')return json(await profile(env,u));
 if(path==='/api/dashboard'&&req.method==='GET')return json(await dashboard(env,u));
 if(path==='/api/health'&&req.method==='GET'){const neg=Number((await env.DB.prepare('SELECT COUNT(*) c FROM quests WHERE user_id=? AND xp_reward<0').bind(u).first())?.c||0);return json({status:neg?'WARNING':'ONLINE',checks:{orphaned:0,negative_xp:neg,negative_money:0}})}
 if(path.startsWith('/api/analytics')&&req.method==='GET'){const url=new URL(req.url);const days=Math.min(365,Math.max(1,Number(url.searchParams.get('days')||30)));const start=new Date(Date.now()-(days-1)*864e5).toISOString().slice(0,10);const rows=[];for(let i=0;i<days;i++){const d=new Date(Date.now()-(days-1-i)*864e5).toISOString().slice(0,10);const x=await env.DB.prepare("SELECT COALESCE(SUM(xp_earned),0) xp, SUM(CASE WHEN status='Complete' THEN 1 ELSE 0 END) done, COUNT(*) total FROM quests WHERE user_id=? AND date=?").bind(u,d).first();rows.push({date:d,xp:Number(x?.xp||0),done:Number(x?.done||0),total:Number(x?.total||0)})}const study=await env.DB.prepare('SELECT COALESCE(SUM(minutes),0) x FROM study_sessions WHERE user_id=? AND date>=?').bind(u,start).first();const fitness=await env.DB.prepare('SELECT COALESCE(SUM(duration),0) x FROM fitness_logs WHERE user_id=? AND date>=?').bind(u,start).first();const quran=await env.DB.prepare('SELECT COALESCE(SUM(pages),0) x FROM quran_logs WHERE user_id=? AND date>=?').bind(u,start).first();const quests=await env.DB.prepare("SELECT COUNT(*) c FROM quests WHERE user_id=? AND status='Complete' AND date>=?").bind(u,start).first();return json({days:rows,totals:{study:Number(study?.x||0),fitness:Number(fitness?.x||0),quranPages:Number(quran?.x||0),quests:Number(quests?.c||0)}})}
 if(path.startsWith('/api/prayer/')&&req.method==='GET'){const d=path.split('/').pop();return json((await env.DB.prepare('SELECT * FROM prayers WHERE user_id=? AND date=?').bind(u,d).first())||{date:d,fajr:0,dhuhr:0,asr:0,maghrib:0,isha:0})}
 if(path.startsWith('/api/day/')&&req.method==='GET'){const d=path.split('/').pop();await ensureDay(env,u,d);return json(await env.DB.prepare('SELECT * FROM daily_logs WHERE user_id=? AND date=?').bind(u,d).first())}
 if(path==='/api/day/close'&&req.method==='POST'){const b=await body(req);const d=b.date||today();await ensureDay(env,u,d);await env.DB.prepare('UPDATE daily_logs SET closed=1 WHERE user_id=? AND date=?').bind(u,d).run();return json({ok:true,nextDate:new Date(new Date(d+'T00:00:00Z').getTime()+864e5).toISOString().slice(0,10)})}
 if(path==='/api/profile'&&req.method==='PATCH'){const b=await body(req);const allowed=['hunter_name','avatar','theme','timezone','currency','academic_year','bac_date','notifications'].filter(k=>Object.hasOwn(b,k));if(allowed.length)await env.DB.prepare(`UPDATE profiles SET ${allowed.map(k=>`${k}=?`).join(',')} WHERE user_id=?`).bind(...allowed.map(k=>b[k]),u).run();return json(await profile(env,u))}
 if(path.startsWith('/api/quests/')&&path.endsWith('/complete')&&req.method==='POST'){const qid=path.split('/')[3];const q=await env.DB.prepare('SELECT * FROM quests WHERE id=? AND user_id=?').bind(qid,u).first();if(!q)return json({error:'Quest not found'},404);if(q.status==='Complete')return json({quest:q,profile:await profile(env,u)});const xp=Math.max(0,Number(q.xp_reward||0)),cr=Math.max(0,Number(q.credit_reward||0));const stm=[env.DB.prepare("UPDATE quests SET status='Complete',xp_earned=?,credits_earned=?,updated_at=? WHERE id=? AND user_id=?").bind(xp,cr,now(),qid,u)];if(cr)stm.push(env.DB.prepare('INSERT INTO credit_transactions(id,user_id,description,date,type,amount,quest_id,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(uid(),u,'Quest: '+q.title,today(),'Quest Reward',cr,qid,now()));if(q.stat_id)stm.push(env.DB.prepare('UPDATE stats SET stat_xp=stat_xp+? WHERE id=? AND user_id=?').bind(xp,q.stat_id,u));if(q.skill_id)stm.push(env.DB.prepare('UPDATE skills SET skill_xp=skill_xp+? WHERE id=? AND user_id=?').bind(xp,q.skill_id,u));await env.DB.batch(stm);if(q.mission_id){const total=Number((await env.DB.prepare('SELECT COUNT(*) c FROM quests WHERE user_id=? AND mission_id=?').bind(u,q.mission_id).first())?.c||0);const done=Number((await env.DB.prepare("SELECT COUNT(*) c FROM quests WHERE user_id=? AND mission_id=? AND status='Complete'").bind(u,q.mission_id).first())?.c||0);const prog=total?Math.round(done/total*100):0;await env.DB.prepare('UPDATE missions SET progress=?,status=? WHERE id=? AND user_id=?').bind(prog,prog===100?'Complete':'Active',q.mission_id,u).run()}return json({quest:await env.DB.prepare('SELECT * FROM quests WHERE id=?').bind(qid).first(),profile:await profile(env,u)})}
 if(path.startsWith('/api/rewards/')&&path.endsWith('/purchase')&&req.method==='POST'){const rid=path.split('/')[3];const r=await env.DB.prepare('SELECT * FROM rewards WHERE id=? AND user_id=?').bind(rid,u).first();const bal=Number((await env.DB.prepare('SELECT COALESCE(SUM(amount),0) x FROM credit_transactions WHERE user_id=?').bind(u).first())?.x||0);if(!r)return json({error:'Reward not found'},404);if(bal<Number(r.cost))return json({error:'Insufficient credits.'},400);await env.DB.prepare('INSERT INTO credit_transactions(id,user_id,description,date,type,amount,reward_id,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(uid(),u,'Reward: '+r.reward,today(),'Reward Purchase',-Math.abs(Number(r.cost)),rid,now()).run();return json({profile:await profile(env,u)})}
 const parts=path.replace(/^\/api\/?/,'').split('/').filter(Boolean),t=parts[0];if(ALLOWED.has(t)){
  if(req.method==='GET'){const r=await env.DB.prepare(`SELECT * FROM ${t} WHERE user_id=? ORDER BY created_at DESC`).bind(u).all();return json(r.results)}
  if(req.method==='POST'){const b=await body(req);const fs=RESOURCE_FIELDS[t];const vals=fs.map(f=>b[f]===undefined?(NUMS.has(f)?0:''):b[f]);const id=uid();const cols=['id','user_id',...fs,'created_at'];await env.DB.prepare(`INSERT INTO ${t} (${cols.join(',')}) VALUES (${cols.map(()=>'?').join(',')})`).bind(id,u,...vals,now()).run();return json(await env.DB.prepare(`SELECT * FROM ${t} WHERE id=? AND user_id=?`).bind(id,u).first(),201)}
  if(parts[1]){const id=parts[1];if(req.method==='PATCH'){const b=await body(req);const fs=RESOURCE_FIELDS[t].filter(k=>Object.hasOwn(b,k));if(fs.length)await env.DB.prepare(`UPDATE ${t} SET ${fs.map(k=>`${k}=?`).join(',')} WHERE id=? AND user_id=?`).bind(...fs.map(k=>b[k]),id,u).run();return json(await env.DB.prepare(`SELECT * FROM ${t} WHERE id=? AND user_id=?`).bind(id,u).first())}if(req.method==='DELETE'){await env.DB.prepare(`DELETE FROM ${t} WHERE id=? AND user_id=?`).bind(id,u).run();return json({ok:true})}}
 }
 return json({error:'Unknown endpoint'},404);
}
export default {async fetch(req,env,ctx){const url=new URL(req.url);if(req.method==='OPTIONS')return new Response(null,{status:204,headers:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PATCH,DELETE,OPTIONS'}});if(url.pathname.startsWith('/api/'))return handleApi(req,env,url.pathname);return env.ASSETS.fetch(req)}};
