name = "the-system-hunter-os"
main = "worker.js"
compatibility_date = "2026-09-26"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "the-system-db"
database_id = "dfe64b8f-9d69-443f-9403-0f462530031d"

[vars]
TOKEN_TTL_SECONDS = "2592000"
